// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stbxvjmuygifgueamybw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0Ynh2am11eWdpZmd1ZWFteWJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4MjU4NjcsImV4cCI6MjA4NzQwMTg2N30.Gjz5Wi5TzNI1_lWyqq9KGELkUa6cn_3FGC_NIKu50eg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});